# nutrition_db.py
# Custom nutrition lookup table: ~200 common foods
# Each entry: { "calories": kcal, "protein": g, "carbs": g, "fat": g, "serving": description }

FOODS = {
    # ── Proteins ──
    "chicken breast": {"calories": 165, "protein": 31, "carbs": 0, "fat": 3.6, "serving": "100g"},
    "chicken thigh": {"calories": 209, "protein": 26, "carbs": 0, "fat": 10.9, "serving": "100g"},
    "chicken wing": {"calories": 203, "protein": 30, "carbs": 0, "fat": 8.1, "serving": "100g"},
    "ground beef 80/20": {"calories": 254, "protein": 17, "carbs": 0, "fat": 20, "serving": "100g"},
    "ground beef 90/10": {"calories": 176, "protein": 20, "carbs": 0, "fat": 10, "serving": "100g"},
    "ground turkey": {"calories": 170, "protein": 21, "carbs": 0, "fat": 9, "serving": "100g"},
    "steak sirloin": {"calories": 206, "protein": 26, "carbs": 0, "fat": 11, "serving": "100g"},
    "steak ribeye": {"calories": 291, "protein": 24, "carbs": 0, "fat": 21, "serving": "100g"},
    "pork chop": {"calories": 231, "protein": 25, "carbs": 0, "fat": 14, "serving": "100g"},
    "pork tenderloin": {"calories": 143, "protein": 26, "carbs": 0, "fat": 3.5, "serving": "100g"},
    "bacon": {"calories": 541, "protein": 37, "carbs": 1, "fat": 42, "serving": "100g"},
    "turkey bacon": {"calories": 218, "protein": 14, "carbs": 2, "fat": 17, "serving": "100g"},
    "salmon": {"calories": 208, "protein": 20, "carbs": 0, "fat": 13, "serving": "100g"},
    "tuna": {"calories": 130, "protein": 29, "carbs": 0, "fat": 1, "serving": "100g"},
    "tuna canned": {"calories": 116, "protein": 26, "carbs": 0, "fat": 0.8, "serving": "100g"},
    "shrimp": {"calories": 99, "protein": 24, "carbs": 0.2, "fat": 0.3, "serving": "100g"},
    "tilapia": {"calories": 96, "protein": 20, "carbs": 0, "fat": 1.7, "serving": "100g"},
    "cod": {"calories": 82, "protein": 18, "carbs": 0, "fat": 0.7, "serving": "100g"},
    "tofu firm": {"calories": 144, "protein": 15, "carbs": 3, "fat": 8, "serving": "100g"},
    "tofu silken": {"calories": 55, "protein": 5, "carbs": 2, "fat": 3, "serving": "100g"},
    "tempeh": {"calories": 192, "protein": 20, "carbs": 8, "fat": 11, "serving": "100g"},
    "turkey breast deli": {"calories": 104, "protein": 18, "carbs": 4, "fat": 1.5, "serving": "100g"},
    "ham deli": {"calories": 145, "protein": 21, "carbs": 2, "fat": 5.5, "serving": "100g"},
    "lamb": {"calories": 282, "protein": 25, "carbs": 0, "fat": 20, "serving": "100g"},
    "bison": {"calories": 143, "protein": 28, "carbs": 0, "fat": 2.4, "serving": "100g"},
    "sausage italian": {"calories": 346, "protein": 14, "carbs": 1, "fat": 31, "serving": "100g"},

    # ── Eggs & Dairy ──
    "egg whole": {"calories": 72, "protein": 6, "carbs": 0.4, "fat": 5, "serving": "1 large"},
    "egg white": {"calories": 17, "protein": 3.6, "carbs": 0.2, "fat": 0.1, "serving": "1 large"},
    "milk whole": {"calories": 149, "protein": 8, "carbs": 12, "fat": 8, "serving": "1 cup"},
    "milk 2%": {"calories": 122, "protein": 8, "carbs": 12, "fat": 4.8, "serving": "1 cup"},
    "milk skim": {"calories": 83, "protein": 8, "carbs": 12, "fat": 0.2, "serving": "1 cup"},
    "almond milk unsweetened": {"calories": 30, "protein": 1, "carbs": 1, "fat": 2.5, "serving": "1 cup"},
    "oat milk": {"calories": 120, "protein": 3, "carbs": 16, "fat": 5, "serving": "1 cup"},
    "greek yogurt plain": {"calories": 100, "protein": 17, "carbs": 6, "fat": 0.7, "serving": "170g"},
    "greek yogurt flavored": {"calories": 150, "protein": 15, "carbs": 18, "fat": 2, "serving": "170g"},
    "yogurt regular": {"calories": 110, "protein": 5, "carbs": 17, "fat": 2, "serving": "170g"},
    "cottage cheese": {"calories": 98, "protein": 11, "carbs": 3.4, "fat": 4.3, "serving": "100g"},
    "cheddar cheese": {"calories": 113, "protein": 7, "carbs": 0.4, "fat": 9.3, "serving": "1 oz"},
    "mozzarella cheese": {"calories": 85, "protein": 6, "carbs": 0.7, "fat": 6.3, "serving": "1 oz"},
    "parmesan cheese": {"calories": 110, "protein": 10, "carbs": 0.9, "fat": 7.3, "serving": "1 oz"},
    "cream cheese": {"calories": 99, "protein": 2, "carbs": 1.6, "fat": 10, "serving": "1 oz"},
    "swiss cheese": {"calories": 106, "protein": 8, "carbs": 0.4, "fat": 7.8, "serving": "1 oz"},
    "butter": {"calories": 102, "protein": 0.1, "carbs": 0, "fat": 11.5, "serving": "1 tbsp"},
    "whey protein powder": {"calories": 120, "protein": 24, "carbs": 3, "fat": 1.5, "serving": "1 scoop"},
    "casein protein powder": {"calories": 120, "protein": 24, "carbs": 4, "fat": 1, "serving": "1 scoop"},

    # ── Grains & Carbs ──
    "white rice cooked": {"calories": 206, "protein": 4.3, "carbs": 45, "fat": 0.4, "serving": "1 cup"},
    "brown rice cooked": {"calories": 216, "protein": 5, "carbs": 45, "fat": 1.8, "serving": "1 cup"},
    "quinoa cooked": {"calories": 222, "protein": 8, "carbs": 39, "fat": 3.5, "serving": "1 cup"},
    "pasta cooked": {"calories": 220, "protein": 8, "carbs": 43, "fat": 1.3, "serving": "1 cup"},
    "whole wheat pasta cooked": {"calories": 174, "protein": 7.5, "carbs": 37, "fat": 0.8, "serving": "1 cup"},
    "oatmeal cooked": {"calories": 154, "protein": 5, "carbs": 27, "fat": 2.6, "serving": "1 cup"},
    "oats dry": {"calories": 150, "protein": 5, "carbs": 27, "fat": 3, "serving": "0.5 cup"},
    "bread white": {"calories": 79, "protein": 2.7, "carbs": 15, "fat": 1, "serving": "1 slice"},
    "bread whole wheat": {"calories": 81, "protein": 4, "carbs": 14, "fat": 1.1, "serving": "1 slice"},
    "bagel plain": {"calories": 270, "protein": 10, "carbs": 53, "fat": 1.5, "serving": "1 bagel"},
    "tortilla flour": {"calories": 146, "protein": 4, "carbs": 24, "fat": 3.5, "serving": "1 medium"},
    "tortilla corn": {"calories": 52, "protein": 1.4, "carbs": 11, "fat": 0.7, "serving": "1 medium"},
    "english muffin": {"calories": 132, "protein": 5, "carbs": 26, "fat": 1, "serving": "1 muffin"},
    "pita bread": {"calories": 165, "protein": 5.5, "carbs": 33, "fat": 0.7, "serving": "1 pita"},
    "pancake": {"calories": 175, "protein": 5, "carbs": 22, "fat": 7, "serving": "1 medium"},
    "waffle": {"calories": 218, "protein": 6, "carbs": 25, "fat": 11, "serving": "1 waffle"},
    "cereal cheerios": {"calories": 100, "protein": 3, "carbs": 20, "fat": 2, "serving": "1 cup"},
    "granola": {"calories": 210, "protein": 5, "carbs": 34, "fat": 7, "serving": "0.5 cup"},
    "couscous cooked": {"calories": 176, "protein": 6, "carbs": 36, "fat": 0.3, "serving": "1 cup"},
    "potato baked": {"calories": 161, "protein": 4.3, "carbs": 37, "fat": 0.2, "serving": "1 medium"},
    "sweet potato baked": {"calories": 103, "protein": 2.3, "carbs": 24, "fat": 0.1, "serving": "1 medium"},
    "french fries": {"calories": 365, "protein": 4, "carbs": 44, "fat": 17, "serving": "1 medium serving"},
    "corn on the cob": {"calories": 88, "protein": 3.3, "carbs": 19, "fat": 1.4, "serving": "1 ear"},
    "popcorn air popped": {"calories": 31, "protein": 1, "carbs": 6, "fat": 0.4, "serving": "1 cup"},
    "crackers saltine": {"calories": 70, "protein": 1.4, "carbs": 12, "fat": 1.8, "serving": "5 crackers"},

    # ── Fruits ──
    "banana": {"calories": 105, "protein": 1.3, "carbs": 27, "fat": 0.4, "serving": "1 medium"},
    "apple": {"calories": 95, "protein": 0.5, "carbs": 25, "fat": 0.3, "serving": "1 medium"},
    "orange": {"calories": 62, "protein": 1.2, "carbs": 15, "fat": 0.2, "serving": "1 medium"},
    "strawberries": {"calories": 46, "protein": 1, "carbs": 11, "fat": 0.4, "serving": "1 cup"},
    "blueberries": {"calories": 84, "protein": 1.1, "carbs": 21, "fat": 0.5, "serving": "1 cup"},
    "grapes": {"calories": 104, "protein": 1.1, "carbs": 27, "fat": 0.2, "serving": "1 cup"},
    "watermelon": {"calories": 46, "protein": 0.9, "carbs": 11, "fat": 0.2, "serving": "1 cup"},
    "pineapple": {"calories": 82, "protein": 0.9, "carbs": 22, "fat": 0.2, "serving": "1 cup"},
    "mango": {"calories": 99, "protein": 1.4, "carbs": 25, "fat": 0.6, "serving": "1 cup"},
    "avocado": {"calories": 240, "protein": 3, "carbs": 13, "fat": 22, "serving": "1 medium"},
    "peach": {"calories": 59, "protein": 1.4, "carbs": 14, "fat": 0.4, "serving": "1 medium"},
    "pear": {"calories": 101, "protein": 0.7, "carbs": 27, "fat": 0.2, "serving": "1 medium"},
    "cherries": {"calories": 87, "protein": 1.5, "carbs": 22, "fat": 0.3, "serving": "1 cup"},
    "cantaloupe": {"calories": 53, "protein": 1.3, "carbs": 13, "fat": 0.3, "serving": "1 cup"},
    "kiwi": {"calories": 42, "protein": 0.8, "carbs": 10, "fat": 0.4, "serving": "1 medium"},
    "raspberries": {"calories": 64, "protein": 1.5, "carbs": 15, "fat": 0.8, "serving": "1 cup"},
    "dried cranberries": {"calories": 123, "protein": 0.1, "carbs": 33, "fat": 0.4, "serving": "0.25 cup"},
    "raisins": {"calories": 129, "protein": 1.3, "carbs": 34, "fat": 0.2, "serving": "0.25 cup"},

    # ── Vegetables ──
    "broccoli": {"calories": 31, "protein": 2.5, "carbs": 6, "fat": 0.4, "serving": "1 cup"},
    "spinach raw": {"calories": 7, "protein": 0.9, "carbs": 1.1, "fat": 0.1, "serving": "1 cup"},
    "spinach cooked": {"calories": 41, "protein": 5.3, "carbs": 7, "fat": 0.5, "serving": "1 cup"},
    "kale": {"calories": 33, "protein": 2.2, "carbs": 6, "fat": 0.6, "serving": "1 cup"},
    "carrots": {"calories": 52, "protein": 1.2, "carbs": 12, "fat": 0.3, "serving": "1 cup"},
    "bell pepper": {"calories": 30, "protein": 1, "carbs": 7, "fat": 0.3, "serving": "1 medium"},
    "onion": {"calories": 44, "protein": 1.2, "carbs": 10, "fat": 0.1, "serving": "1 medium"},
    "tomato": {"calories": 22, "protein": 1.1, "carbs": 4.8, "fat": 0.2, "serving": "1 medium"},
    "cucumber": {"calories": 16, "protein": 0.7, "carbs": 3.1, "fat": 0.2, "serving": "1 cup"},
    "lettuce romaine": {"calories": 8, "protein": 0.6, "carbs": 1.5, "fat": 0.1, "serving": "1 cup"},
    "celery": {"calories": 14, "protein": 0.7, "carbs": 3, "fat": 0.2, "serving": "1 cup"},
    "mushrooms": {"calories": 15, "protein": 2.2, "carbs": 2.3, "fat": 0.2, "serving": "1 cup"},
    "zucchini": {"calories": 20, "protein": 1.5, "carbs": 3.5, "fat": 0.4, "serving": "1 cup"},
    "green beans": {"calories": 34, "protein": 2, "carbs": 8, "fat": 0.1, "serving": "1 cup"},
    "asparagus": {"calories": 27, "protein": 3, "carbs": 5, "fat": 0.2, "serving": "1 cup"},
    "cauliflower": {"calories": 25, "protein": 2, "carbs": 5, "fat": 0.1, "serving": "1 cup"},
    "brussels sprouts": {"calories": 38, "protein": 3, "carbs": 8, "fat": 0.3, "serving": "1 cup"},
    "cabbage": {"calories": 22, "protein": 1, "carbs": 5, "fat": 0.1, "serving": "1 cup"},
    "edamame": {"calories": 188, "protein": 18, "carbs": 14, "fat": 8, "serving": "1 cup"},
    "peas green": {"calories": 118, "protein": 8, "carbs": 21, "fat": 0.6, "serving": "1 cup"},

    # ── Legumes & Nuts ──
    "black beans cooked": {"calories": 227, "protein": 15, "carbs": 41, "fat": 0.9, "serving": "1 cup"},
    "chickpeas cooked": {"calories": 269, "protein": 15, "carbs": 45, "fat": 4.2, "serving": "1 cup"},
    "lentils cooked": {"calories": 230, "protein": 18, "carbs": 40, "fat": 0.8, "serving": "1 cup"},
    "kidney beans cooked": {"calories": 225, "protein": 15, "carbs": 40, "fat": 0.9, "serving": "1 cup"},
    "peanut butter": {"calories": 188, "protein": 8, "carbs": 6, "fat": 16, "serving": "2 tbsp"},
    "almond butter": {"calories": 196, "protein": 7, "carbs": 6, "fat": 18, "serving": "2 tbsp"},
    "almonds": {"calories": 164, "protein": 6, "carbs": 6, "fat": 14, "serving": "1 oz"},
    "walnuts": {"calories": 185, "protein": 4.3, "carbs": 3.9, "fat": 18, "serving": "1 oz"},
    "cashews": {"calories": 157, "protein": 5.2, "carbs": 8.6, "fat": 12, "serving": "1 oz"},
    "pecans": {"calories": 196, "protein": 2.6, "carbs": 3.9, "fat": 20, "serving": "1 oz"},
    "peanuts": {"calories": 161, "protein": 7.3, "carbs": 4.6, "fat": 14, "serving": "1 oz"},
    "sunflower seeds": {"calories": 165, "protein": 5.5, "carbs": 7, "fat": 14, "serving": "1 oz"},
    "chia seeds": {"calories": 138, "protein": 4.7, "carbs": 12, "fat": 8.7, "serving": "1 oz"},
    "flax seeds": {"calories": 150, "protein": 5, "carbs": 8, "fat": 12, "serving": "1 oz"},
    "hummus": {"calories": 166, "protein": 8, "carbs": 14, "fat": 10, "serving": "100g"},
    "trail mix": {"calories": 462, "protein": 13, "carbs": 44, "fat": 29, "serving": "100g"},

    # ── Oils & Condiments ──
    "olive oil": {"calories": 119, "protein": 0, "carbs": 0, "fat": 14, "serving": "1 tbsp"},
    "coconut oil": {"calories": 121, "protein": 0, "carbs": 0, "fat": 13.5, "serving": "1 tbsp"},
    "vegetable oil": {"calories": 120, "protein": 0, "carbs": 0, "fat": 14, "serving": "1 tbsp"},
    "mayo": {"calories": 94, "protein": 0.1, "carbs": 0.1, "fat": 10, "serving": "1 tbsp"},
    "ketchup": {"calories": 20, "protein": 0.2, "carbs": 5, "fat": 0, "serving": "1 tbsp"},
    "mustard": {"calories": 3, "protein": 0.2, "carbs": 0.3, "fat": 0.2, "serving": "1 tsp"},
    "soy sauce": {"calories": 9, "protein": 0.9, "carbs": 1, "fat": 0, "serving": "1 tbsp"},
    "salsa": {"calories": 36, "protein": 2, "carbs": 8, "fat": 0.2, "serving": "0.5 cup"},
    "ranch dressing": {"calories": 73, "protein": 0.4, "carbs": 1, "fat": 7.7, "serving": "1 tbsp"},
    "balsamic vinegar": {"calories": 14, "protein": 0.1, "carbs": 2.7, "fat": 0, "serving": "1 tbsp"},
    "honey": {"calories": 64, "protein": 0.1, "carbs": 17, "fat": 0, "serving": "1 tbsp"},
    "maple syrup": {"calories": 52, "protein": 0, "carbs": 13, "fat": 0, "serving": "1 tbsp"},
    "jam": {"calories": 56, "protein": 0.1, "carbs": 14, "fat": 0, "serving": "1 tbsp"},

    # ── Snacks & Prepared ──
    "protein bar": {"calories": 230, "protein": 20, "carbs": 25, "fat": 8, "serving": "1 bar"},
    "granola bar": {"calories": 140, "protein": 3, "carbs": 25, "fat": 4, "serving": "1 bar"},
    "chips potato": {"calories": 152, "protein": 2, "carbs": 15, "fat": 10, "serving": "1 oz"},
    "chips tortilla": {"calories": 142, "protein": 2, "carbs": 18, "fat": 7, "serving": "1 oz"},
    "pretzels": {"calories": 108, "protein": 3, "carbs": 23, "fat": 1, "serving": "1 oz"},
    "dark chocolate": {"calories": 170, "protein": 2, "carbs": 13, "fat": 12, "serving": "1 oz"},
    "ice cream vanilla": {"calories": 137, "protein": 2.3, "carbs": 16, "fat": 7.3, "serving": "0.5 cup"},
    "pizza cheese slice": {"calories": 272, "protein": 12, "carbs": 34, "fat": 10, "serving": "1 slice"},
    "pizza pepperoni slice": {"calories": 298, "protein": 13, "carbs": 34, "fat": 12, "serving": "1 slice"},
    "burger beef patty": {"calories": 254, "protein": 17, "carbs": 0, "fat": 20, "serving": "100g"},
    "hot dog": {"calories": 151, "protein": 5, "carbs": 2, "fat": 13, "serving": "1 link"},
    "mac and cheese": {"calories": 310, "protein": 11, "carbs": 36, "fat": 14, "serving": "1 cup"},
    "burrito chicken": {"calories": 500, "protein": 28, "carbs": 55, "fat": 18, "serving": "1 burrito"},
    "sushi california roll": {"calories": 255, "protein": 9, "carbs": 38, "fat": 7, "serving": "6 pieces"},
    "sushi salmon roll": {"calories": 304, "protein": 14, "carbs": 42, "fat": 8, "serving": "6 pieces"},
    "ramen instant": {"calories": 380, "protein": 10, "carbs": 52, "fat": 14, "serving": "1 packet"},
    "fried rice": {"calories": 238, "protein": 6, "carbs": 34, "fat": 8, "serving": "1 cup"},
    "caesar salad": {"calories": 180, "protein": 7, "carbs": 10, "fat": 12, "serving": "1 serving"},
    "grilled cheese sandwich": {"calories": 366, "protein": 14, "carbs": 28, "fat": 23, "serving": "1 sandwich"},
    "pbj sandwich": {"calories": 376, "protein": 13, "carbs": 50, "fat": 15, "serving": "1 sandwich"},
    "chicken nuggets": {"calories": 296, "protein": 15, "carbs": 16, "fat": 19, "serving": "6 pieces"},
    "taco beef": {"calories": 210, "protein": 9, "carbs": 21, "fat": 10, "serving": "1 taco"},
    "sub sandwich turkey": {"calories": 280, "protein": 18, "carbs": 36, "fat": 6, "serving": "6 inch"},
    "soup chicken noodle": {"calories": 175, "protein": 12, "carbs": 20, "fat": 5, "serving": "1 cup"},

    # ── Drinks ──
    "orange juice": {"calories": 112, "protein": 1.7, "carbs": 26, "fat": 0.5, "serving": "1 cup"},
    "apple juice": {"calories": 114, "protein": 0.3, "carbs": 28, "fat": 0.3, "serving": "1 cup"},
    "coca cola": {"calories": 140, "protein": 0, "carbs": 39, "fat": 0, "serving": "12 oz"},
    "sprite": {"calories": 140, "protein": 0, "carbs": 38, "fat": 0, "serving": "12 oz"},
    "gatorade": {"calories": 80, "protein": 0, "carbs": 21, "fat": 0, "serving": "12 oz"},
    "coffee black": {"calories": 2, "protein": 0.3, "carbs": 0, "fat": 0, "serving": "1 cup"},
    "latte whole milk": {"calories": 150, "protein": 8, "carbs": 13, "fat": 6, "serving": "12 oz"},
    "cappuccino": {"calories": 80, "protein": 4, "carbs": 6, "fat": 4, "serving": "8 oz"},
    "smoothie fruit": {"calories": 210, "protein": 3, "carbs": 50, "fat": 0.5, "serving": "16 oz"},
    "protein shake": {"calories": 200, "protein": 30, "carbs": 12, "fat": 4, "serving": "16 oz"},
    "beer regular": {"calories": 153, "protein": 1.6, "carbs": 13, "fat": 0, "serving": "12 oz"},
    "beer light": {"calories": 103, "protein": 0.9, "carbs": 6, "fat": 0, "serving": "12 oz"},
    "wine red": {"calories": 125, "protein": 0.1, "carbs": 4, "fat": 0, "serving": "5 oz"},
    "wine white": {"calories": 121, "protein": 0.1, "carbs": 4, "fat": 0, "serving": "5 oz"},
    "energy drink": {"calories": 110, "protein": 0, "carbs": 28, "fat": 0, "serving": "8 oz"},
    "coconut water": {"calories": 46, "protein": 2, "carbs": 9, "fat": 0.5, "serving": "1 cup"},
    "chocolate milk": {"calories": 208, "protein": 8, "carbs": 26, "fat": 8.5, "serving": "1 cup"},

    # ── Breakfast ──
    "overnight oats": {"calories": 300, "protein": 11, "carbs": 44, "fat": 9, "serving": "1 cup"},
    "french toast": {"calories": 149, "protein": 5, "carbs": 16, "fat": 7, "serving": "1 slice"},
    "breakfast burrito": {"calories": 350, "protein": 18, "carbs": 30, "fat": 17, "serving": "1 burrito"},
    "acai bowl": {"calories": 380, "protein": 6, "carbs": 62, "fat": 12, "serving": "1 bowl"},
    "croissant": {"calories": 231, "protein": 5, "carbs": 26, "fat": 12, "serving": "1 medium"},
    "muffin blueberry": {"calories": 426, "protein": 6, "carbs": 62, "fat": 17, "serving": "1 large"},
    "donut glazed": {"calories": 269, "protein": 4, "carbs": 31, "fat": 15, "serving": "1 medium"},

    # ── Misc ──
    "rice cake": {"calories": 35, "protein": 0.7, "carbs": 7, "fat": 0.3, "serving": "1 cake"},
    "beef jerky": {"calories": 116, "protein": 9, "carbs": 3, "fat": 7, "serving": "1 oz"},
    "string cheese": {"calories": 80, "protein": 7, "carbs": 1, "fat": 5, "serving": "1 stick"},
    "guacamole": {"calories": 150, "protein": 2, "carbs": 8, "fat": 13, "serving": "100g"},
}


def search_foods(query):
    """Search foods by keyword. Returns list of (name, data) tuples."""
    query = query.lower().strip()
    if not query:
        return []
    results = []
    for name, data in FOODS.items():
        if query in name:
            results.append((name, data))
    results.sort(key=lambda x: x[0].index(query) if query in x[0] else 999)
    return results[:20]


def get_food(name):
    """Get exact food data by name. Returns dict or None."""
    return FOODS.get(name.lower().strip())
